# wrangler.toml
name = 'amazon-redirect'
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "amazon-redirect-worker"

[env.staging]
name = "amazon-redirect-worker-staging"